### ISSUE TITLE
관리자 회원 목록 중 비회원 정보가 보이는 오류

### ISSUE THREAD

**Issue by Antonio-990510** [hansung-pocs/blog-android#220]
**버그에 대해 자세히 설명**
관리자 페이지에서 회원 목록 중에 비회원인데 학번과 기수가 표시되는 것들이 몇몇 개가 있습니다.

**버그 재현 과정**
1. 관리자 페이지에 진입한다
2. 회원 목록을 누른다.
3. 스크롤 한다.
4. 익명 회원 중 이상한 것들이 있다.

**예상 결과**
![image](https://user-images.githubusercontent.com/83750244/187065380-2e0f6fdb-c30e-4315-904b-c51fc9b47a75.png)

**실제 결과**
![image](https://user-images.githubusercontent.com/83750244/187065390-503576e9-5a5c-4814-9065-aa93ad99860c.png)

**환경**
- API level: 30

**Comment by jja08111** [comment]
리사이클러 뷰에서 값을 제대로 초기화하지 않아 발생한것으로 추측됩니다.
