### ISSUE TITLE
마크다운 줄넘김 오류

### ISSUE THREAD

**Issue by Antonio-990510** [hansung-pocs/blog-android#221]
**버그에 대해 자세히 설명**
마크다운에서 줄 띄우기가 안됨

**버그 재현 과정**
1. 글 작성 페이지 진입한다
2. 마크다운을 아래와 같이 작성한다.
![image](https://user-images.githubusercontent.com/83750244/187065552-c5037d34-a2e5-4621-93a7-81824a21f0cf.png)

**예상 결과**
![image](https://user-images.githubusercontent.com/83750244/187065532-b5cabd16-d40d-4e8c-b33a-6b1b5b79c101.png)

**실제 결과**
![image](https://user-images.githubusercontent.com/83750244/187065540-1a7ec6ba-795b-4edf-831b-35d59c221c6e.png)

**환경**
- API level: 30

**Comment by jja08111** [comment]
https://ko.wikipedia.org/wiki/마크다운 을 확인해보면 문장 끝에 띄어쓰기 두 개를 해야지 줄바꿈이 된다고 하네요. 확인해보니 정상 작동합니다. 감사합니다.
