### ISSUE TITLE
회원 탈퇴 후 회원 목록 반영 안됨

### ISSUE THREAD

**Issue by Antonio-990510** [hansung-pocs/blog-android#222]
**버그에 대해 자세히 설명**
관리자가 회원 탈퇴시킨 후 뒤로 가면 회원 목록에 남아있음

**버그 재현 과정**
1. 회원목록 페이지에 진입한다
2. 회원를 누른다.
3. 회원을 강퇴한다.
4. 뒤로 가기 버튼을 누른다.

**예상 결과**
![image](https://user-images.githubusercontent.com/83750244/187066359-cfbc5bc5-62ec-4534-af9b-ea7be7ebe9c3.png)

**실제 결과**
![image](https://user-images.githubusercontent.com/83750244/187066350-9e0f274b-a0cb-4428-811a-8a347995cfeb.png)
namegg를 강퇴 했지만 남아있고, 새로고침 후 사라지는 것을 발견 할 수있다.

**환경**
- API level: 30

**Comment by jja08111** [comment]
setResult를 활용하여 해결할 수 있어보이네요.
